# Generated by Django 4.1.2 on 2022-11-10 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['last_name'], 'verbose_name': 'Students', 'verbose_name_plural': 'Students'},
        ),
        migrations.AlterField(
            model_name='student',
            name='edu_level',
            field=models.CharField(max_length=1, verbose_name='Klasa'),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(max_length=9),
        ),
        migrations.AlterField(
            model_name='student',
            name='school',
            field=models.CharField(choices=[('Primary School', 'Primary School'), ('High School', 'High School')], max_length=25),
        ),
    ]
