# Generated by Django 3.2.12 on 2022-12-08 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_student_options_alter_student_edu_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.teacher'),
        ),
    ]
